#!/usr/bin/env node

var fetchPage = require('./lib/fetch_page');
var parseBody = require('./lib/parse_body');
var displayResult = require('./lib/display_result');

function main() {
  var args = process.argv.splice(2);
  if (args.length === 0) {
    console.error('Usage: ydict-client <word or phrase>');
    process.exit(1);
  }
  var keyword = args.join(' ');

  fetchPage(keyword, function(error, body) {
    if (error) throw new Error(error);
    var result = parseBody(body);
    displayResult(keyword, result);
  });
}

if (require.main === module) {
  main();
}
